### ISSUE TITLE
Add restoring last state

### ISSUE THREAD

**Issue by avzhuiko** [avzhuiko/climate-remote-control#3]
When I reboot HA, all parameters on climate card become default.

Expected: All settings which was set up should not become default

**Comment by N3rd7** [comment]
Hi! I was looking for documentation about my question and found this closed issue which might be related: the integration keeps memory of the last temperature used, however after I reboot HA, the temperature when turning on the unit (heat or cool) is 16. The other parameters (swing and fan speed) are maintained after reboot. Is there a way to change so it recalls the last temperature selected after reboot? Or maybe select a default temperature (other than 16)?
